### ISSUE TITLE
where is stabilizer package implement

### ISSUE THREAD

**Issue by waveness** [Isawan/Stabilizer#1]
？？？
import stabilizer.util as util
import stabilizer.identify as identify
import stabilizer.match as match
import stabilizer.transform as transform
import stabilizer.geometry as geometry

**Comment by Isawan** [comment]
You'll find it in stable.py

The function you must call is `stable.stable_video(video)`.
The parameter is an iterable object that yields 2D numpy arrays i.e. the frame of the video. 
The function returns a generator that yields 2D numpy arrays, each is a frame that has been stablized.

Sorry about the messy code, this whole project was coded up within 2 weeks for a University assignment.
